// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoYHLkxe3K4_Jx__oZm1FblQm0OdqC95o',
    appId: '1:773520984019:web:2dcac79870bb82930b5126',
    messagingSenderId: '773520984019',
    projectId: 'hts-lunchapp',
    authDomain: 'hts-lunchapp.firebaseapp.com',
    storageBucket: 'hts-lunchapp.appspot.com',
    measurementId: 'G-6X44H02C7Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzHnYTwbgFYkhcSO628PuWM77W-Tv5mTs',
    appId: '1:773520984019:android:a0120ae7b5a165870b5126',
    messagingSenderId: '773520984019',
    projectId: 'hts-lunchapp',
    storageBucket: 'hts-lunchapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxTB0FCNZbBrg3_HUZD8fxum3bjK9PdOY',
    appId: '1:773520984019:ios:a29f74730aa3a8e00b5126',
    messagingSenderId: '773520984019',
    projectId: 'hts-lunchapp',
    storageBucket: 'hts-lunchapp.appspot.com',
    androidClientId: '773520984019-v93p8uj5gbfkiuqgdihg3mcq52g56nqi.apps.googleusercontent.com',
    iosClientId: '773520984019-c28modlbcj8heki4aeelr4p20rodlc7n.apps.googleusercontent.com',
    iosBundleId: 'com.romarioburke.HLa.hla',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxTB0FCNZbBrg3_HUZD8fxum3bjK9PdOY',
    appId: '1:773520984019:ios:5bcbf1b0b2c010290b5126',
    messagingSenderId: '773520984019',
    projectId: 'hts-lunchapp',
    storageBucket: 'hts-lunchapp.appspot.com',
    androidClientId: '773520984019-v93p8uj5gbfkiuqgdihg3mcq52g56nqi.apps.googleusercontent.com',
    iosClientId: '773520984019-vheo50f9vhct5lnb3ik5uncg0up5ahje.apps.googleusercontent.com',
    iosBundleId: 'com.romarioburke.HLa.hla.RunnerTests',
  );
}
